Update jenkinsfile_new

diff --git a/jenkinsfile_new b/jenkinsfile_new
--- a/jenkinsfile_new
+++ b/jenkinsfile_new
@@ -1,45 +1,51 @@
-pipeline{
+
+pipeline {
     agent any
 
-    stages{
-        stage('scm'){
-            steps{
+    environment {
+        DOCKER_IMAGE = 'alpine:3.21.2'
+        DOCKER_CREDENTIALS_ID = 'ayaz4'
+        SSH_CREDENTIALS_ID = 'server-ssh-credentials'
+        DEPLOY_SERVER = '13.213.72.254'
+    }
+
+    stages {
+        stage('Checkout Code') {
+            steps {
                 checkout scm
             }
         }
-        stage('build'){
-            steps{
-                sh 'mvn clean install'
+
+        stage('Build Docker Image') {
+            steps {
+                script {
+                    docker.withRegistry('https://index.docker.io/v1/', ayaz4) {
+                        def appImage = docker.build("${alpine:3.21.2}:${env.BUILD_NUMBER}")
+                        alpine:3.21.2.push()
+                    }
+                }
             }
         }
-        stage('nexus'){
-            steps{
-                nexusArtifactUploader artifacts: [
-                    [artifactId: 'onlinebookstore', 
-                    classifier: '', 
-                    file: '/var/lib/jenkins/workspace/Application/target/onlinebookstore-0.0.1-SNAPSHOT.war', 
-                    type: 'war']
-                    ], 
-                    credentialsId: 'nexus', 
-                    groupId: 'onlinebookstore', 
-                    nexusUrl: '47.129.46.77:8081', 
-                    nexusVersion: 'nexus3', 
-                    protocol: 'http', 
-                    repository: 'webapp', 
-                    version: '0.0.1-SNAPSHOT'
+
+        stage('Deploy Application') {
+            steps {
+                sshagent([SSH_CREDENTIALS_ID]) {
+                    sh "ssh -o StrictHostKeyChecking=no user@${DEPLOY_SERVER} \
+                    'docker pull ${alpine:3.21.2}:${env.BUILD_NUMBER} && \
+                    docker stop app || true && \
+                    docker rm app || true && \
+                    docker run -d --name app -p 8080:8080 ${alpine:3.21.2}:${env.BUILD_NUMBER}'"
+                }
             }
         }
-        stage('deploy'){
-            steps{
-                deploy adapters: 
-                [tomcat9(
-                    credentialsId: 'tomcat', 
-                    path: '', 
-                    url: 'http://47.129.46.77:8082/')
-                    ], 
-                    contextPath: null, 
-                    war: '**/*.war'
-            }
+    }
+
+    post {
+        success {
+            echo 'Deployment successful!'
+        }
+        failure {
+            echo 'Deployment failed!'
         }
     }
 }
